"use strict";

const libxmljs = require('libxmljs');

exports._newElement = (doc, name, content) => new libxmljs.Element(doc, name, content);
exports.elementAddNode = name => content => element => () => element.node(name, content);
exports.elementName = element => () => element.name();
exports.elementSetName = name => element => () => element.name(name);
exports.elementText = element => () => element.text();
exports.elementSetText = text => element => () => element.text(text);
exports._elementAttr = name => element => () => element.attr(name);
exports.elementSetAttr = name => value => element => () => element.attr(name, value);
exports.elementAttrs = element => () => element.attrs();
exports.elementChildNodes = element => () => element.childNodes();
exports.elementAddChild = child => element => () => element.addChild(child);
exports._elementNextElement = element => () => element.nextElement();
exports._elementPrevElement = element => () => element.prevElement();
exports.elementAddNextSibling = siblingNode => element => () => element.addNextSibling(siblingNode);
exports.elementAddPrevSibling = siblingNode => element => () => element.addPrevSibling(siblingNode);
exports._elementFind = xpath => element => () => element.find(xpath);
exports._elementFindWithNS = xpath => nsUri => element => () => element.find(xpath, nsUri);
exports.elementReplaceWithElement = replacement => element => () => element.replace(replacement);
exports.elementReplaceWithText = text => element => () => element.replace(text);
exports.elementPath = element => () => element.path();
exports.elementDefineNS = href => element => () => element.defineNamespace(href);
exports.elementDefineNSwithPrefix = prefix => href => element => () => element.defineNamespace(prefix, href);
exports._elementNS = element => () => element.namespace();
exports.elementSetNS = ns => element => () => element.namespace(ns);
exports.elementSetNShref = href => element => () => element.namespace(href);
exports.elementSetNShrefWithPrefix = prefix => href => element => () => element.namespace(prefix, href);
exports.elementClearNS = element => () => element.namespace(null);
exports.elementAllNS = element => () => element.namespaces();
